### ISSUE TITLE
[Suggestion]Porting to Fabric 1.20.1 or newer

### ISSUE THREAD

**Issue by JDogHLM** [paulevsGitch/BetterWeather#5] opened 2024-03-27 19:16 UTC
Hello, I am extremely interested in your mod for my modpack, but I discovered that the mod was developed for Minecraft 1.7.3. Do you have any plans to make a port of this mod for fabric/forge Minecraft 1.20.x? This is an extremely impeccable weather mod that is missing in modern versions of the game. There is nothing similar at the moment.

**Comment by paulevsGitch** [comment] 2024-03-28 07:49
Duplicate of #3

**Closed by paulevsGitch** 2024-03-28 07:49 UTC

**Comment by paulevsGitch** [comment] 2024-03-28 08:02
> Minecraft 1.7.3

For Minecraft beta 1.7.3, not for Minecraft release 1.7.3
